# -*- restclient -*-

# Create Post
POST http://localhost:8123/api/v1/posts
Content-type: application/json

{
"title": "This is my title",
"text": "This is my text",
"public": true
}

# Get Posts
GET http://localhost:8123/api/v1/posts

# Get Posts with title filtering
GET http://localhost:8123/api/v1/posts?title=hello

# Get Posts with sorting
GET http://localhost:8123/api/v1/posts?sort=title

# Get Posts with sorting in desc order
GET http://localhost:8123/api/v1/posts?sort=title_desc

# Invalid sort query
GET http://localhost:8123/api/v1/posts?sort=123

# Get Posts with pagination
GET http://localhost:8123/api/v1/posts?page=2

# Get Posts with no results
GET http://localhost:8123/api/v1/posts?title=goodbye

# Get Read-Only Link
GET http://localhost:8123/api/v1/posts/6783

# Get Admin Link
GET http://localhost:8123/api/v1/posts/486

# Get link that doesn't exist
GET http://localhost:8123/api/v1/posts/12345

# Get link with invalid id
GET http://localhost:8123/api/v1/posts/h1

# Report a Post
POST http://localhost:8123/api/v1/posts/6772/reports
Content-type: application/json

{
"reason": "inappropriate content"
}

# Report a Post using a write id
POST http://localhost:8123/api/v1/posts/486/reports
Content-type: application/json

{
"reason": "This is a read-only action, not an admin action."
}

# Update a Post with only title
PUT http://localhost:8123/api/v1/posts/486
Content-type: application/json

{
"title": "New Title!"
}

# Update a Post with title, text, and public
PUT http://localhost:8123/api/v1/posts/486
Content-type: application/json

{
"title": "New Title Again!",
"text": "New Text!",
"public": false
}

# Update a Post using Read-only link
PUT http://localhost:8123/api/v1/posts/6783
Content-type: application/json

{
"title": "I'm Not Authorized"
}

# Delete a Post
DELETE http://localhost:8123/api/v1/posts/486

# Delete a Post using Read-only link
DELETE http://localhost:8123/api/v1/posts/6783


# Request Not Found | Any request not supported by the API
GET http://localhost:8123/api/v1/helloworld