# -*- restclient -*-

# Create Post
POST http://localhost:8123/api/v1/posts
Content-type: application/json

{
"title": "my 6th post",
"text": "this is my 6th post.",
"public": true
}

# Get Posts
GET http://localhost:8123/api/v1/posts/808